### PR TITLE
Add log with timestamp option (#63)

### LINKED ISSUE #63: log with timestamp
it would be helpful to be able to track when things happened in the log, for example #64. currently the log lines don't include timestamps. i would suggest adding them.

### PR DESCRIPTION
**Pull request by Focshole**
Added option to have timestamp in logs, fixes #63 and partially #56

### CODE REVIEW

**Comment by HarHarLinks** [comment]
Well done overall, just a small mishap:
This PR contains commits intended for both #63 und #64.
If you look at the history in a tree structure (https://github.com/Focshole/pacoloco/network or [`git log --graph --oneline --all`](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git)), it becomes obvious what happened:
image

Your fix-63 branch has the fix-64 branch as its ancestor and hence inherits its commit.
What likely happened (and I should have pointed this out before) is you created the fix-64 branch and immediately continued to creating the fix-63 branch. This is one of the purposes of the `git checkout master` command I gave. When you create a new branch, it will use the currently checked out branch as starting point. Since you didn't go back to master, the fix-64 branch is your starting point. To fix it you could delete the branch and retry or learn some more 😉:
1. `git checkout fix-63` to say "i want to work on this branch"
2. `git reset --hard master`  to reset the fix-63 branch to the state of master. this will "delete" the 2 commits and any pending changes. you are now at the same state as if you had just done `git checkout master && git checkout -b fix-63`.
3. cherry pick or edit whatever #63 needs
4. add and commit
5. `git push`: git will see that you pushed previously to this branch on github and refuse to do it as it is not in sync with your local work. `git push --force` to overwrite the current state on github with your local state.

If you want to learn about git basics, I can really recommend you try out https://ohmygit.org. It's great strength is that is visualizes what is going on when you use these abstract git commands really well.

**Comment by Focshole** [comment]
I do always end up with terrible unexpected issues when i mess up with git history, I had heard about https://ohmygit.org/ , never got the time and energy to try it out in my free time. Thank you!

**Comment by HarHarLinks** [comment]
This looks great, I hope it can be merged soon. Thank you for your work!

**Comment by Focshole** [comment]
Thank you for the help with git! I have cleaned also the fix-7 branch now :)

**Pull request merged**
