### PR TITLE
Prefetching fix

### PR DESCRIPTION
**Pull request by Focshole**
The prefetching commit had some issues, wrote everything about it below

### CODE REVIEW

**Review by Focshole — COMMENTED** [review]
I had left 3 huge errors:

- The insertion of all the available packages on the mirror was extremely slow cause I didn't do a batch insertion
- The filename regex was too strict, `epoch/version` can include `+` or `_`, and `arch` field possibly too
- The prefetch links are wrong, the "path" field is missing, I should finish fixing it in a few hours

I can't squash commits, each time I get quite bad issues I can't solve, which can be noticed from the troublesome history of this pull request.

**Comment by Focshole** [comment]
I just have tested all the fixes on real hardware, I had to wait until some packages were available to be prefetched, it worked flawless so far. I think there are no more big issues with this code.
So far, some unpleasant behaviour may be:
- Prefetching procedure does not take into account of priorities expressed in the config files when many URLs are given for a single repo, it would require some work to provide another sorting index which should be updated each time pacoloco starts
- If a mirror is down and no client have ever requested a db file from another mirror in the url set, the prefetching procedure would prefetch nothing (until a client requests a db update)

**Review by Focshole — COMMENTED** [review]
Added space after // in comments, should be all ready to be merged

**Comment by anatol** [comment]
Hi Moreno. I pulled your commit, rebased on top of the current master and cleaned it a little bit. Please check/test it and let me know if it is ready for an additional round of review.

**Review by Focshole — COMMENTED** [review]
It should be fine now, I don't see any more issues so far

**Comment by anatol** [comment]
Merged. Thank you for your work!

**Pull request merged**
